name: echo hello
run-name: ${{ github.event_name == 'workflow_dispatch' && '[Manual]' || '[Auto]' }} Deploy Frontend - ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:

jobs:
  echo-branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello!
